mlflow:
  tracking_uri: 'https://mlflow-demo.atypon.com/'
  experiment_name: 'Default'
  run_name: 'doc2vec_sparse_0_23'
model:
  objective: 'binary'
  tree_learner: 'data'
  verbosity: -1
  n_jobs: 15
  metric: 'auc'
  random_state: 42
data:
  datasets: ['aminer', 'pubmed', 'zbmath', 'kisti', 'arnetminer']
  default_embeddings: True
  #external_embeddings_dir: 'external_embeddings/random_embedder'
  external_embeddings_dir: None
results:
  results_folder: 'results'
  model_path: 'models/lightgbm_sparse_0_23.joblib'