mlflow:
  tracking_uri: http://0.0.0.0:8000 #'https://mlflow-demo.atypon.com/'
  experiment_name: 'AND-lightgbm-training'
  run_name: 'new-data-improvements'
model:
  objective: 'binary'
  tree_learner: 'data'
  verbosity: -1
  n_jobs: 15
  metric: 'auc'
  random_state: 42
data:
  datasets: ['aminer', 'pubmed', 'zbmath', 'kisti', 'arnetminer']
  external_embeddings_dir: Null
results:
  results_folder: 'results'
  model_path: 'models/lightgbm.joblib'