mlflow:
  tracking_uri: 'file:mlruns' # Can be remote server as well eg https://my-tracking-server:5000
  experiment_name: 'AND-lightgbm-training'
  run_name: 'doc2vec_sparse_0_23'
datasets: ['aminer', 'pubmed', 'zbmath', 'kisti', 'arnetminer']
default_embeddings: True
#external_embeddings_dir: 'external_embeddings/random_embedder'
external_embeddings_dir: None
model_path: 'models/lightgbm_sparse_0_23.joblib'