mlflow:
  tracking_uri: https://mlflow-demo.atypon.com/
  experiment_name: 'AND-lightgbm-training'
  run_name: 'model-retrain'
model:
  objective: 'binary'
  tree_learner: 'data'
  verbosity: -1
  n_jobs: 15
  metric: 'auc'
  random_state: 42
  #monotone_constraints: [0, 0, 0, 0, 0, 1, 0, 0]
  monotone_constraints_method: advanced
  lambda_l1: 0.6
  max_depth: 5
  num_leaves: 8
  max_bin: 128
data:
  datasets: ['aminer', 'pubmed', 'zbmath', 'kisti', 'arnetminer']
  external_embeddings_dir: Null
features:
  - operation: cosine_similarity
    field: paperVector
    categorical: False
  - operation: levenshtein
    field: authorNormName
    categorical: False
  - operation: jaccard_similarity
    field: affiliationIds
    categorical: False
  - operation: jaccard_similarity
    field: coAuthorShortNormNames_old
    categorical: False
  - operation: equality
    field: s2AuthorId
    categorical: True
  - operation: equality
    field: orcId
    categorical: True
  - operation: normalized_by_authors_absolute_difference
    field: authorPositionNo
    operation_args:
      normalization_field: coAuthorShortNormNames_old
    categorical: False
  - operation: absolute_difference
    field: pubYear
    categorical: False
results:
  results_folder: 'results'
  model_path: 'models/lightgbm.joblib'