mlflow:
  tracking_uri: http://0.0.0.0:8000 #'https://mlflow-demo.atypon.com/'
  experiment_name: AND-clustering
  run_name: clusterer-new-datasets
datasets: ['aminer', 'pubmed', 'zbmath', 'kisti', 'arnetminer'] # ['aminer', 'pubmed', 'zbmath', 'kisti', 'arnetminer']
model_source: 'models/lightgbm.joblib'
features:
  - operation: cosine_similarity
    field: paperVector
  - operation: levenshtein
    field: authorNormName
  - operation: jaccard_similarity
    field: affiliationIds
  - operation: jaccard_similarity
    field: coAuthorShortNormNames_old
  - operation: equality
    field: s2AuthorId
  - operation: equality
    field: orcId
  - operation: normalized_by_authors_absolute_difference
    field: authorPositionNo
    operation_args:
      normalization_field: coAuthorShortNormNames_old
  - operation: absolute_difference
    field: pubYear
external_embeddings_dir: Null