num_pairs: 100
dataset: pubmed
model_path: models/lightgbm.joblib
result_path: results/unit_test.json
features:
  - operation: cosine_similarity
    field: paperVector
  - operation: levenshtein
    field: authorNormName
  - operation: jaccard_similarity
    field: affiliationIds
  - operation: jaccard_similarity
    field: coAuthorShortNormNames_old
  - operation: equality
    field: s2AuthorId
  - operation: equality
    field: orcId
  - operation: normalized_by_authors_absolute_difference
    field: authorPositionNo
    operation_args:
      normalization_field: coAuthorShortNormNames_old
  - operation: absolute_difference
    field: pubYear